package my.tools.csv.nameformatter;

public class GlobalReporting {
	
	public static int FIRST_AND_INITIALS_CNT,FIRST_AND_TWO_INITIALS_CNT,FIRST_INITIAL_LAST_CNT;
	public static int FIRST_LAST_INITIAL_CNT,FIRST_LAST_CNT,FIRST_MIDDLE_LAST_CNT;
	public static int LAST_COMMA_FIRST_INITIAL_CNT,LAST_COMMA_FIRST_MIDDLE_CNT,LAST_COMMA_FIRST_CNT;
	public static int LAST_WITH_SPACE_COMMA_FIRST_CNT,MIDDLE_LAST_COMMA_FIRST_CNT,TWO_LAST_COMMA_FIRST_MIDDLE_CNT;
	public static int LAST_COMMA_FIRST_TWO_MIDDLE_CNT,FOUR_NAMES_CNT,FIRST_COMMA_INITIALS_CNT;
	public static int LAST_FIRST_MIDDLE_CNT,LAST_FIRST_CNT;
	public static void report() {
		
		
		System.out.println("FIRST_AND_INITIALS_CNT:"+FIRST_AND_INITIALS_CNT);		
		System.out.println("FIRST_AND_TWO_INITIALS_CNT:"+FIRST_AND_TWO_INITIALS_CNT);
		System.out.println("FIRST_INITIAL_LAST_CNT:"+FIRST_INITIAL_LAST_CNT);
		System.out.println("FIRST_LAST_INITIAL_CNT:"+FIRST_LAST_INITIAL_CNT);
		System.out.println("FIRST_LAST_CNT:"+FIRST_LAST_CNT);
		System.out.println("FIRST_MIDDLE_LAST_CNT:"+FIRST_MIDDLE_LAST_CNT);
		System.out.println("LAST_COMMA_FIRST_INITIAL_CNT:"+LAST_COMMA_FIRST_INITIAL_CNT);
		System.out.println("LAST_COMMA_FIRST_MIDDLE_CNT:"+LAST_COMMA_FIRST_MIDDLE_CNT);
		System.out.println("LAST_COMMA_FIRST_CNT:"+LAST_COMMA_FIRST_CNT);
		System.out.println("LAST_WITH_SPACE_COMMA_FIRST_CNT:"+LAST_WITH_SPACE_COMMA_FIRST_CNT);	
		System.out.println("MIDDLE_LAST_COMMA_FIRST_CNT:"+MIDDLE_LAST_COMMA_FIRST_CNT);	
		System.out.println("TWO_LAST_COMMA_FIRST_MIDDLE_CNT:"+TWO_LAST_COMMA_FIRST_MIDDLE_CNT);
		System.out.println("LAST_COMMA_FIRST_TWO_MIDDLE_CNT:"+LAST_COMMA_FIRST_TWO_MIDDLE_CNT);
		System.out.println("FOUR_NAMES_CNT:"+FOUR_NAMES_CNT);
		System.out.println("FIRST_COMMA_INITIALS_CNT:"+FIRST_COMMA_INITIALS_CNT);
		System.out.println("LAST_FIRST_CNT:"+LAST_FIRST_CNT);
		
	}
	
}
