package my.tools.csv.nameformatter.patterns;

public enum Patterns {
	
	LAST_MIDDLE_FIRST,FIRST_MIDDLE_LAST,LAST_FIRST_MIDDLE,
	LAST_COMMA_MIDDLE_FIRST,LAST_COMMA_FIRST_MIDDLE,
	LAST_FIRST,FIRST_LAST,
	LAST_COMMA_FIRST,
	FIRST_M_L,FIRST_L_M,LAST_F_M,LAST_M_F,
	FIRST_L,LAST_F
	
}
